In [1]:
import  pandas as pd
import numpy as np
import json
from pandas import json_normalize
import matplotlib.pyplot as plt
pd.set_option('future.no_silent_downcasting', True)
import matplotlib.ticker as mticker
import ast
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import warnings
import re
from datetime import datetime

In [3]:
df = pd.read_csv("dataset_clean.csv")

df

C:\Users\Mohamed\AppData\Local\Temp\ipykernel_32396\871467979.py:1: DtypeWarning: Columns (0,10,11,12,16,18,19,20,21,22,23,24,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("dataset_clean.csv")

,url,contrat,type,prix,titre,description,surface,pieces,etage,code_postal,...,prox_transport,has_piscine,has_parking,has_garage,has_jardin,has_terrasse,has_ascenseur,has_climatisation,has_balcon,has_gardien
0,https://www.monbien.tn/properties/7592/coquet-...,vente,appartement,140000.0,Coquet studio à vendre à 140 md à hammamet 513...,Réf: AH077 Nabeul / Hammamet Appartement / à v...,NaN,2.0,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
1,https://www.monbien.tn/properties/7588/villa-t...,vente,maison,650000.0,Villa toute neuve s+3 avec piscine à hammamet ...,Réf: MHS186 Nabeul / Hammamet Villa / à vendre...,200.0,4.0,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
2,https://www.monbien.tn/properties/7596/un-dupl...,vente,terrain,730000.0,Un duplex avec piscine à hammamet nord à vendr...,Réf: MH112 Nabeul / Hammamet nord Duplex / à v...,220.0,4.0,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
3,https://www.monbien.tn/properties/7594/apparte...,vente,appartement,320000.0,Appartement s+1 avec vue de mer à hammamet à v...,Réf: AH079 Nabeul / Hammamet centre Appartemen...,76.0,2.0,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
4,https://www.monbien.tn/properties/7602/terrain...,vente,terrain,60000.0,Terrain de 400 m² avec vue de mer à hammamet s...,Réf: THS156 Nabeul / Hammamet Terrain / à vend...,400.0,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50664,NaN,location,appartement,1650.0,MENZAH 9 B : APPARTEMENT S+2 À LOUER,📍MENZAH 9 B : APPARTEMENT S+2 À LOUER \n\nL’a...,120.0,NaN,NaN,NaN,...,0,0,1,0,0,0,0,0,0,0
50665,NaN,location,autre,1450.0,📍ENNASR 2 : REZ-DE-CHAUSSÉE D’UNE VILLA S+2 À...,L’agence #MON_RÈSEAU met à la location un rez-...,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
50666,NaN,location,maison,4200.0,📍 El MENZAH 6 À LOUER – VILLA S+7 USAGE BUREAU...,📍 El MENZAH 6 À LOUER – VILLA S+7 USAGE BUREAU...,600.0,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
50667,NaN,location,bureau,1150.0,📍 CITE ENNOZHA - ARIANA : DES BUREAUX H+2 À LOUER,L’agence #MON_RÉSEAU met à la location des bur...,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
50668,NaN,location,appartement,1200.0,ENNASR 2 : APPARTEMENT S+1 RICHEMENT MEUBLÉ A ...,📍ENNASR 2 : APPARTEMENT S+1 RICHEMENT MEUBLÉ A...,70.0,NaN,NaN,NaN,...,0,0,1,0,0,0,0,0,1,0

In [4]:
print (df["contrat"].value_counts())

contrat
location             35898
vente                13670
commercial             866
location vacances      206
achat                   15
partage                 12
autre                    2
Name: count, dtype: int64

In [6]:
df[df["contrat"] == "autre"]

,url,contrat,type,prix,titre,description,surface,pieces,etage,code_postal,...,prox_transport,has_piscine,has_parking,has_garage,has_jardin,has_terrasse,has_ascenseur,has_climatisation,has_balcon,has_gardien
20963,https://www.immobilier.com.tn/annonce/5990/ame...,autre,autre,NaN,Neuf : Américain Médical Center lac 2 - immobi...,Avenue du Dollar 1053 Les Berges du Lac - Tuni...,70.0,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
21834,https://www.immobilier.com.tn/annonce/23252/re...,autre,appartement,2900.0,Neuf : Résidence Très haut standing aux jardin...,Avenue du Dollar 1053 Les Berges du Lac - Tuni...,260.0,4.0,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.loc[df["url"] == "https://www.immobilier.com.tn/annonce/23252/residence-tres-haut-standing-aux-jardins-de-carthage", "contrat"] = "location"

In [ ]:
df.drop(df[df["contrat"] in ["autre", "commercial", "achat", "partage", "location vacances"]].index, inplace=True)

In [5]:
print (df["type"].value_counts())

type
appartement         19815
maison              10464
local commercial     6894
terrain              5290
bureau               4447
autre                3759
Name: count, dtype: int64

In [7]:
df[df["type"] == "autre"]

,url,contrat,type,prix,titre,description,surface,pieces,etage,code_postal,...,prox_transport,has_piscine,has_parking,has_garage,has_jardin,has_terrasse,has_ascenseur,has_climatisation,has_balcon,has_gardien
30,https://www.monbien.tn/properties/7556/fond-de...,vente,autre,30000.0,Fond de commerce gusto à vendre au kram est,Réf: OF94315 Tunis / Le kram Fonds de commerce...,40.0,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
34,https://www.monbien.tn/properties/7565/maison-...,vente,autre,180000.0,Maison s+2 avec garage et jardin à hammamet su...,Réf: MHS149 Nabeul / Hammamet Maison / à vendr...,NaN,3.0,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
40,https://www.monbien.tn/properties/7546/maison-...,vente,autre,235000.0,Maison arabe s+2 renouvelée à vendre à hammame...,Réf: MH127 Nabeul / Hammamet Maison / à vendre...,NaN,3.0,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
62,https://www.monbien.tn/properties/7500/fond-de...,vente,autre,98000.0,Fond de commerce elvora à vendre au centre vil...,Réf: OF94519 Tunis / Bab bhar Fonds de commerc...,1000.0,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
63,https://www.monbien.tn/properties/7513/maison-...,vente,autre,160000.0,Maison s+3 avec titre bleu à vendre à korba 51...,Réf: MK006 Nabeul / Korba Maison / à vendre il...,NaN,4.0,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50631,NaN,location,autre,1450.0,📍ENNASR 2 : REZ-DE-CHAUSSÉE D’UNE VILLA S+2 À...,L’agence #MON_RÈSEAU met à la location un rez-...,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
50638,NaN,location,autre,1700.0,📍ENNASR 2 : REZ-DE-CHAUSSÉE D’UNE VILLA S+2 R...,L’agence #MON_RÈSEAU met à la location un rez-...,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
50648,NaN,location,autre,1450.0,📍ENNASR 2 : REZ-DE-CHAUSSÉE D’UNE VILLA S+2 À...,L’agence #MON_RÈSEAU met à la location un rez-...,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
50655,NaN,location,autre,1700.0,📍ENNASR 2 : REZ-DE-CHAUSSÉE D’UNE VILLA S+2 R...,L’agence #MON_RÈSEAU met à la location un rez-...,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
50665,NaN,location,autre,1450.0,📍ENNASR 2 : REZ-DE-CHAUSSÉE D’UNE VILLA S+2 À...,L’agence #MON_RÈSEAU met à la location un rez-...,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0